export const items = [
  {
    id: "1",
    title: "The Final Mission",
    description: "An elite agent embarks on his last dangerous operation.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie1.mp4",
    duration: "1:45:30",
    releaseYear: 2023,
    genre: ["Action", "Adventure"],
  },
  {
    id: "2",
    title: "Shadows of Tomorrow",
    description: "In a world where the sun never rises, one man holds the key.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie2.mp4",
    duration: "2:00:00",
    releaseYear: 2022,
    genre: ["Sci-Fi", "Thriller"],
  },
  {
    id: "3",
    title: "Echoes of the Past",
    description: "A historian discovers a secret that changes everything.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie3.mp4",
    duration: "1:30:00",
    releaseYear: 2021,
    genre: ["Drama", "Mystery"],
  },
  {
    id: "4",
    title: "Midnight Drive",
    description: "A getaway driver is pulled into a heist gone wrong.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie4.mp4",
    duration: "1:50:20",
    releaseYear: 2023,
    genre: ["Action", "Crime"],
  },
  {
    id: "5",
    title: "Underwater Kingdom",
    description: "A diver uncovers an ancient civilization beneath the sea.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie5.mp4",
    duration: "2:10:00",
    releaseYear: 2020,
    genre: ["Fantasy", "Adventure"],
  },
  {
    id: "6",
    title: "Code Blue",
    description: "A young doctor must choose between rules and saving lives.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie6.mp4",
    duration: "1:38:45",
    releaseYear: 2023,
    genre: ["Drama"],
  },
  {
    id: "7",
    title: "Neon Skies",
    description: "In a cyberpunk future, a hacker searches for redemption.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie7.mp4",
    duration: "1:55:10",
    releaseYear: 2024,
    genre: ["Sci-Fi", "Action"],
  },
  {
    id: "8",
    title: "The Painter",
    description: "A mysterious artist hides a past full of secrets.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie8.mp4",
    duration: "1:42:00",
    releaseYear: 2021,
    genre: ["Mystery", "Drama"],
  },
  {
    id: "9",
    title: "Ghost Frequency",
    description: "A radio DJ hears voices that shouldn't exist.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie9.mp4",
    duration: "1:36:30",
    releaseYear: 2022,
    genre: ["Horror", "Thriller"],
  },
  {
    id: "10",
    title: "Parallel",
    description: "Two lives collide across alternate dimensions.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie10.mp4",
    duration: "1:48:00",
    releaseYear: 2023,
    genre: ["Sci-Fi", "Romance"],
  },
  {
    id: "11",
    title: "Crescendo",
    description: "A gifted pianist must overcome her past to find her sound.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie11.mp4",
    duration: "1:40:15",
    releaseYear: 2020,
    genre: ["Drama", "Music"],
  },
  {
    id: "12",
    title: "The Reckoning",
    description:
      "A former detective reopens a cold case that hits too close to home.",
    thumbnailUrl: "/images/thumbnails/thumbnail1.jpg",
    videoUrl: "/videos/movie12.mp4",
    duration: "2:03:20",
    releaseYear: 2024,
    genre: ["Crime", "Thriller"],
  },
];
